#! /bin/sh

# wallpaper
feh --no-fehbg --randomize --bg-scale $HOME/.config/bspwm/backgrounds/*

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
		let name++
	done
}
workspaces

bspc config border_width         3
bspc config window_gap           6
bspc config split_ratio          0.52

bspc config focused_border_color "#89DCEB"
bspc config normal_border_color "#575268"
bspc config active_border_color "#F5E0DC"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst nm-applet xfce4-power-manager ksuperkey

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Launch keybindings daemon
sxhkd &

# Launch NetworkManager applet
nm-applet &

# Enable power management
xfce4-power-manager &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --experimental-backends --config $HOME/.config/bspwm/picom.conf &
