#!/bin/env bash

source colors

FONT="JetBrainsMono Nerd Font:size=12"

# configuration of j4-dmenu-desktop
j4-dmenu-desktop --no-generic --term="alacritty" --dmenu="dmenu -p 'Run App:' -c -i -l 10 -nb \"$bg\" -nf \"$fg\" -sb \"$altbg\" -sf \"$fg\" -fn \"$FONT\""
