#!/bin/bash
# shellcheck disable=SC2086

## Get colors -----------------
source colors

FG="$fg"
BG="$bg"

BLACK="#161320"
RED="#F28FAD"
GREEN="#ABE9B3"
YELLOW="#FAE3B0"
BLUE="#96CDFB"
MAGENTA="#DDB6F2"
CYAN="#B5E8E0"
WHITE="#D9E0EE"

TOTD=$(fortune -n 90 -s | head -n 1)

## Exec	-----------------
i3lock \
--color="${BG}D9"			\
\
--insidever-color=${GREEN}	\
--insidewrong-color=${RED}	\
--inside-color="${BG}00"	\
\
--ringver-color=${GREEN}	\
--ringwrong-color=${RED}	\
--ring-color=${CYAN}		\
\
--line-color=${BG}			\
--separator-color=${BG}		\
\
--keyhl-color=${YELLOW}		\
--bshl-color=${RED}			\
\
--verif-color=${BG}			\
--wrong-color=${FG}			\
--layout-color=${FG}		\
\
--time-color=${FG}			\
--date-color=${FG}			\
\
--pass-media-keys			\
--pass-screen-keys			\
--pass-power-keys			\
--pass-volume-keys			\
--{time,date,layout,verif,wrong,greeter}-font="JetBransMono Nerd Font"			\
--{layout,verif,wrong,greeter}-size=18							\
--time-size=34													\
--date-size=18													\
--greeter-text="${TOTD}"			\
--greeter-color=${FG}				\
--verif-text="verifying..."			\
--wrong-text="error!"				\
--noinput-text="Empty"				\
--lock-text="Locking..."			\
--lockfailed-text="Failed to lock"	\
--radius 140				\
--ring-width 8.0			\
--screen 1					\
--clock						\
--indicator					\
--time-str="%I:%M:%S %p"		\
--date-str="%A, %b %d, %G"
#--blur 5
